---
deployment:
  tasks:
    - source ~/.bashrc
    - cd /home/$USERNAME/public_html/cl-maker
    - composer install --no-dev --optimize-autoloader
    # Comment this line if web application was production version
    - php artisan migrate:refresh --seed
    # -----------------------------------------------------------
    - php artisan optimize:clear